openapi: 3.0.1
info:
  title: 对象存储API
  version: 1.0.0
servers:
- url: http://example.com
tags:
- name: 对象操作
  description: ""
paths:
  /object_storage/api/vendors/{vendor_name}/buckets/{bucket_name}/objects:
    post:
      tags:
      - 对象操作
      summary: 创建并上传对象
      parameters:
      - name: bucket_name
        description: 桶名称
        required: true
        in: path
        schema:
          type: string
      - name: X-OS-COPY-SOURCE-KEY
        description: 复制的源对象KEY
        required: false
        in: header
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                object_key:
                  type: string
                  description: 对象KEY（即路径）
                  required: true
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: 成功
          content:
            'application/json':
              schema:
                allOf:
                - $ref: '#/components/schemas/Status'
                - type: object
                  properties:
                    object:
                      $ref: '#/components/schemas/Object'

  /object_storage/api/vendors/{vendor_name}/buckets/{bucket_name}/objects/{object_key}:
    get:
      tags:
      - 对象操作
      summary: 获取对象详情
      parameters:
      - name: object_key
        description: 对象KEY
        required: true
        in: path
        schema:
          type: string
      responses:
        200:
          description: 成功
          content:
            'application/json':
              schema:
                allOf:
                - $ref: '#/components/schemas/Status'
                - type: object
                  properties:
                    object:
                      $ref: '#/components/schemas/Object'

    put:
      tags:
      - 对象操作
      summary: 上传对象
      parameters:
      - name: object_key
        description: 对象KEY
        required: true
        in: path
        schema:
          type: string
      - name: X-OS-COPY-SOURCE-KEY
        description: 复制的源对象KEY
        required: false
        in: header
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                object_key:
                  type: string
                  description: object_kind为`dir`时必选
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: 成功
          content:
            'application/json':
              schema:
                allOf:
                - $ref: '#/components/schemas/Status'
                - type: object
                  properties:
                    object:
                      $ref: '#/components/schemas/Object'

    delete:
      tags:
      - 对象操作
      summary: 删除对象
      parameters:
      - name: object_key
        description: 对象KEY
        required: true
        in: path
        schema:
          type: string
      responses:
        200:
          description: 成功
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Status'

  /object_storage/api/vendors/{vendor_name}/buckets/{bucket_name}/objects/{object_key}/uploads:
    post:
      tags:
      - 对象操作
      summary: 创建分段上传
      parameters:
      - name: object_key
        description: 对象KEY
        required: true
        in: path
        schema:
          type: string
      responses:
        200:
          description: 成功
          content:
            'application/json':
              schema:
                allOf:
                - $ref: '#/components/schemas/Status'
                - type: object
                  properties:
                    upload_id:
                      type: string
                      description: 分段上传ID

  /object_storage/api/vendors/{vendor_name}/buckets/{bucket_name}/objects/{object_key}/uploads/{upload_id}/eof:
    post:
      tags:
      - 对象操作
      summary: 完成分段上传
      parameters:
      - name: object_key
        description: 对象KEY
        required: true
        in: path
        schema:
          type: string
      - name: upload_id
        description: 分段上传ID
        required: true
        in: path
        schema:
          type: string
      responses:
        200:
          description: 成功
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Status'

  /object_storage/api/vendors/{vendor_name}/buckets/{bucket_name}/objects/{object_key}/uploads/{upload_id}:
    delete:
      tags:
      - 对象操作
      summary: 取消分段上传
      parameters:
      - name: object_key
        description: 对象KEY
        required: true
        in: path
        schema:
          type: string
      - name: upload_id
        description: 分段上传ID
        required: true
        in: path
        schema:
          type: string
      responses:
        200:
          description: 成功
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Status'

  /object_storage/api/vendors/{vendor_name}/buckets/{bucket_name}/objects/{object_key}/uploads/{upload_id}/parts:
    get:
      tags:
      - 对象操作
      summary: 获取已上传片段
      parameters:
      - name: object_key
        description: 对象KEY
        required: true
        in: path
        schema:
          type: string
      - name: upload_id
        description: 分段上传ID
        required: true
        in: path
        schema:
          type: string
      responses:
        200:
          description: 成功
          content:
            'application/json':
              schema:
                allOf:
                - $ref: '#/components/schemas/Status'
                - type: object
                  properties:
                    object:
                      $ref: '#/components/schemas/ObjectPart'

    post:
      tags:
      - 对象操作
      summary: 上传片段
      parameters:
      - name: bucket_name
        description: 桶名称
        required: true
        in: path
        schema:
          type: string
      - name: object_key
        description: 对象KEY
        required: true
        in: path
        schema:
          type: string
      - name: upload_id
        description: 分段上传ID
        required: true
        in: path
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: 成功
          content:
            'application/json':
              schema:
                allOf:
                - $ref: '#/components/schemas/Status'
                - type: object
                  properties:
                    object:
                      $ref: '#/components/schemas/ObjectPart'

components:
  schemas:
    Status:
      type: object
      properties:
        errcode:
          type: number
          description: 错误码，1000为成功
          example: 1000
        msg:
          type: string
          description: 错误信息
    Object:
      type: object
      description: 文件对象
      properties:
        vendor_name:
          type: string
          description: 厂家名称
        bucket_name:
          type: string
          description: 桶名称
        object_key:
          type: string
          description: 对象KEY（即路径）
        content_type:
          type: string
          description: 文件类型
        content_length:
          type: number
          description: 文件大小
        etag:
          type: string
          description:
        last_modified:
          type: string
          description: 最后修改时间
    ObjectPart:
      type: object
      description: 文件对象分片
      properties:
        vendor_name:
          type: string
          description: 厂家名称
        bucket_name:
          type: string
          description: 桶名称
        object_key:
          type: string
          description: 对象KEY（即路径）
        part_num:
          type: number
          description: 片段序列
        size:
          type: number
          description: 片段大小
        etag:
          type: string
          description:
        last_modified:
          type: string
          description: 最后修改时间
